### ISSUE TITLE
UnboundLocalError: local variable 'temp_results' referenced before assignment

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [metageni/SUPER-FOCUS#38]
[2019-02-26 12:31:08,398 - INFO]    Parsing Alignments
Traceback (most recent call last):
  File "/home/allnutt.t/.conda/envs/py3/bin/superfocus", line 11, in <module>
    sys.exit(main())
  File "/home/allnutt.t/.conda/envs/py3/lib/python3.7/site-packages/superfocus_app/superfocus.py", line 322, in main
    minimum_identity, minimum_alignment, subsystems_translation, aligner)
  File "/home/allnutt.t/.conda/envs/py3/lib/python3.7/site-packages/superfocus_app/do_alignment.py", line 171, in parse_alignments
    update_results(results, sample_index, temp_results, normalise, number_samples)
UnboundLocalError: local variable 'temp_results' referenced before assignment

**Comment by theo-allnutt-bioinformatics** [comment]
I think this error might be caused by some of my input files having very few reads (they were mapping results). When they were excluded it went away.

**Comment by metageni** [comment]
@theo-allnutt-bioinformatics thanks for reporting it. I feel like this problem was addressed already. Which version of the program are you using?

This should not happen on version 0.33.
